### PR TITLE
[246] fixed sendUserViolation() with wrong email Response 404 Not found

### PR DESCRIPTION
**Pull request by ushh789**
For valid data, except for the email 
```
{
"email": "Test1gmail.com",
"language": "en",
"name": "Test1",
"violationDescription": "124125sfgg"
}
```

image

### CODE REVIEW

**Comment by BerserkrMM** [comment]
image
image
image
by the way, under ADMIN it gives 404

**Comment by ushh789** [comment]
> image
> image
> image
> by the way, under ADMIN it gives 404

I haven't tested this with User right, because the task was to check email...
Anyways, the 401 response might be a problem in the future, so I might add an issue to fix it.
Thanks for review!

**Review by RockTF — APPROVED** [review]

**Review by RockTF — APPROVED** [review]

**Review by IliaWithHat — COMMENTED** [review]
Flip if else block. Should read like this: if user exist by email than send email, else throw error. Negation in this place are confusing.

**Comment by ushh789** [comment]
> Flip if else block. Should read like this: if user exist by email than send email, else throw error. Negation in this place are confusing.

Thanks for review, just made a commit where I have changed the if-else block, please review again.

**Review by IliaWithHat — APPROVED** [review]

**Review by tellmant — APPROVED** [review]

**Pull request merged**
