### PR TITLE
[215] added email regex validation for sendHabitNotification()

### PR DESCRIPTION
**Pull request by ushh789**
If invalid email is given, BadRequestException will be thrown with message:
image

### CODE REVIEW

**Comment by nataliiapovzhyk** [comment]
add @Email to the field class SendHabitNotification 
and @Valid annotation to Email Controller instead of regex

@PostMapping("/sendHabitNotification")
    public ResponseEntity<Object> sendHabitNotification(@RequestBody !!!!! **@Valid**!!!!!!! SendHabitNotification sendHabitNotification) {
        emailService.sendHabitNotification(sendHabitNotification.getName(), sendHabitNotification.getEmail());
        return ResponseEntity.status(HttpStatus.OK).build();
    }


public class SendHabitNotification implements Serializable {
    private String name;

    @Email
    private String email;
}

**Review by nataliiapovzhyk — DISMISSED** [review]
use @Valid and @Email for BodyParameters
it will throw propore response code - bad request with clear explanation:
image

**Comment by ushh789** [comment]
> use @Valid and @Email for BodyParameters
> it will throw propore response code - bad request with clear explanation:
> image

Thanks for your review! I've also fixed the bug with sendHabitNotification() in [this](https://github.com/OlhenShu/ProjectStage_Team1_May/issues/213#issue-2297856160) issue. As you can see there we check **userRepo.existsUserByEmail(email)** before calling **sendEmail(email, subject, content)**. I tried adding annotations @Email and @Valid but in this case we always get 404 response code

I suggest to combine my existing solutions so we get:

```
if (email.matches(AppConstant.VALIDATION_EMAIL)){
            if (!userRepo.existsUserByEmail(email)) {
                throw new NotFoundException(ErrorMessage.USER_NOT_FOUND_BY_EMAIL + email);
            }
            sendEmail(email, subject, content);
        } else {
            throw new BadRequestException("Email " + email + " is not valid");
        }
```
In my opinion, that's the best solution. Let me know what you think.

**Comment by BerserkrMM** [comment]
I would simplify a bit:
`if (!email.matches(AppConstant.VALIDATION_EMAIL)) {
            throw new BadRequestException("Email " + email + " is not valid");
        }
        if (!userRepo.existsUserByEmail(email)) {
            throw new NotFoundException(ErrorMessage.USER_NOT_FOUND_BY_EMAIL + email);
        }
        sendEmail(email, subject, content);`

**Review by BerserkrMM — APPROVED** [review]

**Review by RockTF — APPROVED** [review]

**Review by IliaWithHat — APPROVED** [review]

**Pull request merged**
